### PR TITLE
[Fix comment] expr8 rules are wrong

### PR DESCRIPTION
**Pull request by tyru**
Maybe expr8 rules are wrong.

### CODE REVIEW

**Comment by k-takata** [comment]
These are came from Vim's eval.txt. So it should be also updated.

**Comment by tyru** [comment]
Thanks for investigating!
I'll send PR to vim/vim too.

**Comment by tyru** [comment]
Sent. https://github.com/vim/vim/pull/3320

**Comment by tyru** [comment]
eval.txt were updated.
https://github.com/vim/vim/commit/fc65cabb15d0236bce001ad78e12a40511caf941#diff-bea881dfa9626bab7141337b0fcdb23e

**Comment by tyru** [comment]
Thank you for follow up 😄

**Pull request closed without merging**
