### PR TITLE
fix(parse): fix read_nonwhite get dead loop

### PR DESCRIPTION
**Pull request by iamcco**
fix https://github.com/vim-jp/vim-vimlparser/issues/144

### CODE REVIEW

**Comment by tyru** [comment]
@iamcco
`js/vimlparser.js` and `py/vimlparser.py` is generated from `autoload/vimlparser.vim`.
so could you fix `autoload/vimlparser.vim` and run `make` to generate js and py files?

**Comment by tyru** [comment]
and please also commit js, py files.

**Comment by iamcco** [comment]
Done

**Comment by tyru** [comment]
Thanks! 🎉

**Pull request merged**
