### PR TITLE
get_token_sq_c: skip char2nr for fixed values

### PR DESCRIPTION
**Pull request by blueyed**
In Python it would use `ord()`, which does not work for `"\e"`.

But apart from that `viml_char2nr` should probably be made to support/handle `\e`?
(Note however that "\e" is an invalid escape sequence in Python, so should be `r"\e"` there then)

### CODE REVIEW

**Comment by tyru** [comment]
I want to merge this but codecov failed?
I don't know codecov and how to see that info...

**Comment by blueyed** [comment]
It "just" reports that the code in this PR/diff is not covered: https://codecov.io/gh/vim-jp/vim-vimlparser/compare/045da67d201b4f334c3c2ce0ad77abbf3a9be5ee...d3bca7fed5144d64959b86c59220e50d08d094c3

I've not checked if that's the case really (or if it is due to covimerage not handling this correctly) - but it should not block us from merging it.
It's just an indicator that the code is not tested, and would be more critical for new code (where it shows that a test is missing).

**Comment by blueyed** [comment]
Check the "Diff" tab - https://codecov.io/gh/vim-jp/vim-vimlparser/compare/045da67d201b4f334c3c2ce0ad77abbf3a9be5ee...d3bca7fed5144d64959b86c59220e50d08d094c3/diff

**Comment by tyru** [comment]
@blueyed Okay, thanks!

**Pull request merged**
