### PR TITLE
ci: coverage for Python

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by blueyed** [comment]
Coverage for the py file: https://codecov.io/gh/vim-jp/vim-vimlparser/src/c7975ab891de23b23f36feaaf46e94eb97311062/py/vimlparser.py

**Comment by blueyed** [comment]
Oh.. coverage needs to be appended with the python runs already.

**Comment by blueyed** [comment]
Better/good: https://codecov.io/gh/vim-jp/vim-vimlparser/src/3d5ec96e4fc0973fa0a0327ec6af2bacf6f91db4/py/vimlparser.py

**Comment by blueyed** [comment]
@tyru 
I cannot merge it myself.
But it is OK to wait a bit for other feedback if that's what you want.

**Comment by tyru** [comment]
I thought you had permission to merge.
merged it.

**Pull request merged**
