### PR TITLE
Update py/vimlparser.py

### PR DESCRIPTION
**Pull request by Kuniwak**
This patch is only for updating py/vimlparser.py to deec9bdb.

### CODE REVIEW

**Comment by Kuniwak** [comment]
Oooops...

```
$ python py/vimlparser.py
  File "py/vimlparser.py", line 2496
    lambda = token.type == TOKEN_ARROW
           ^
SyntaxError: invalid syntax
```

**Comment by Kuniwak** [comment]
I added the patch cad6197.
In this patch, I applied `s/lambda/lambda_/` to avoid using reserved keyword of Python.

**Comment by mattn** [comment]
LGTM but please wait @haya14busa

**Comment by haya14busa** [comment]
You should not add patch to the generated code. 

You can change identifier name in pycompiler.py instead

**Comment by haya14busa** [comment]
example: https://github.com/vim-jp/vim-vimlparser/blob/deec9bdbc8739cee5a51ab9023cdc0ef48c3546b/js/jscompiler.vim#L803-L804

I think you can get it.

**Comment by blueyed** [comment]
So https://github.com/vim-jp/vim-vimlparser/blob/deec9bdbc8739cee5a51ab9023cdc0ef48c3546b/py/pycompiler.vim should be used (and fixed for the lambda)?!

**Comment by blueyed** [comment]
See https://github.com/vim-jp/vim-vimlparser/pull/45 for handling all reserved keywords.

**Comment by blueyed** [comment]
Should get updated / superseded after #45 / #46 are in.

**Comment by blueyed** [comment]
Included in https://github.com/vim-jp/vim-vimlparser/pull/45 now.

**Pull request closed without merging**
