### PR TITLE
Allow function name which starts with underscore

### LINKED ISSUE #133: vimlparser doesn't allow function name which starts with '_'
via https://github.com/iamcco/vim-language-server/issues/9

### PR DESCRIPTION
**Pull request by tyru**
Fix #133

### CODE REVIEW

**Comment by blueyed** [comment]
LGTM, needs to generate py/js.

**Comment by blueyed** [comment]
Should we only run Travis for master branches (from origin) - or should we use forks for PRs?
(I mean that here Travis ran two times, for the PR and then also for the branch on the main repo)

**Comment by tyru** [comment]
travis-ci/pr and travis-ci/push is checks the pull request branch and merged branch (I forgot which one check that).
master may be changed after push, so we need both.

**Comment by tyru** [comment]
thanks for view.

**Comment by tyru** [comment]
s/view/review/

**Comment by blueyed** [comment]
> travis-ci/pr and travis-ci/push check the pull request branch and merged branch (I forgot which one check that).
> master may be changed after push, so we need both.

The important one is the "pr" check (which tests the merge with master).
The other checks the branch as-is (and there it might pass, although it fails for the merge).
Therefore usually testing "pr" for PRs is fine - and happens when creating the PR from a fork (and not the main repo).  When using the main repo for PRs also, you usually configure Travis to only build the master branch, and release tags.

**Pull request merged**
