### PR TITLE
Support binary number literals (e.g. 0b0, 0b1011)

### PR DESCRIPTION
**Pull request by tyru**
I found Vim script has binary number literals (e.g. 0b0, 0b1011), and they are not supported yet.
Fixed tokenizer to support it.

Sorry, I don't check from when the literal format is supported...

### CODE REVIEW

**Comment by tyru** [comment]
I added test cases:

* "0B..." (large B)
* "0X..." (large X) (I found tests were missing)

**Comment by rhysd** [comment]
> I found Vim script has binary number literals (e.g. 0b0, 0b1011)

しらなかった…

**Comment by tyru** [comment]
We should handle this too?

> Vim script，:echo 0b0123 は :echo 0b01 23 に解釈されるのね…エラーじゃないのか

https://twitter.com/Linda_pp/status/1040620461921427456

**Comment by tyru** [comment]
> :echo 0b0123 は :echo 0b01 23

It seems to work already. added a test.

**Comment by tyru** [comment]
I will merge this at 9/15 24:00

**Comment by k-takata** [comment]
> I found Vim script has binary number literals (e.g. 0b0, 0b1011)

FYI, This was introduced by 7.4.1027.

**Comment by tyru** [comment]
Thanks for checking!

**Pull request merged**
