### PR TITLE
fix incorrect E477

### LINKED ISSUE #20: Incorrect E477
In a function in my vimrc, I use `Gdiff!`. Using `vint --json .vimrc`, I get:

```
[{"severity": "error", "file_path": ".vimrc", "line_number": 588, "reference": "ynkdir/vim-vimlparser", "column_number": 3, "description": "E477: No ! allowed", "policy_name": "SyntaxError"}]
```

### PR DESCRIPTION
**Pull request by haya14busa**
BANG should be allowed for user defined cmd

fix #20

### CODE REVIEW

**Comment by wsdjeg** [comment]
I have a file ginit.vim for neovim-qt, and the context is
```vim
if exists("g:GuiLoaded")
    Guifont! DejaVu Sans Mono for Powerline:h11:cANSI:qDRAFT
endif
```
but I got error E477, BTW, this command is defined in other plugins, not in my dotfiles.
before this issue has beed fixed, I need change it to:
```vim
if exists("g:GuiLoaded")
    exe 'Guifont! DejaVu Sans Mono for Powerline:h11:cANSI:qDRAFT'
endif
```

**Comment by blueyed** [comment]
FWIW, I came up with this patch (before finding this PR):
```diff
diff --git i/py/vimlparser.py w/py/vimlparser.py
index 09d41cf..f030eaa 100644
--- i/py/vimlparser.py
+++ w/py/vimlparser.py
@@ -797,8 +797,10 @@ def parse_command(self):
             self.ea.forceit = 1
         else:
             self.ea.forceit = 0
-        if not viml_eqregh(self.ea.cmd.flags, "\\<BANG\\>") and self.ea.forceit:
-            raise VimLParserException(Err("E477: No ! allowed", self.ea.cmdpos))
+        if self.ea.cmd.flags != 'USERCMD':
+            # With USERCMDs BANG is not parsed currently.
+            if not viml_eqregh(self.ea.cmd.flags, "\\<BANG\\>") and self.ea.forceit:
+                raise VimLParserException(Err("E477: No ! allowed", self.ea.cmdpos))
         if self.ea.cmd.name != "!":
             self.reader.skip_white()
         self.ea.argpos = self.reader.getpos()
```

**Comment by mattn** [comment]
Could you please add test?

**Comment by mattn** [comment]
test_command passed. thank you

**Pull request merged**
