### PR TITLE
delfunction: add BANG to flags

### PR DESCRIPTION
**Pull request by blueyed**
`delfunction! Foo` is valid.

### CODE REVIEW

**Comment by tyru** [comment]
Could you add a test?

**Comment by blueyed** [comment]
Hmm, not sure if it makes sense.
It's basically coming through the definition.

But if required, where should it go?

**Comment by tyru** [comment]
> It's basically coming through the definition.

Yes, I want to add a test to ensure that behavior will not break in the future.

> where should it go?

1. You can add the following files.
2. Run `make test` to see the results.

test/test_delfunction.ok

```
(delfunction F)
(delfunction F)
```

test/test_delfunction.vim

```vim
delfunction F
delfunction! F
```

**Comment by blueyed** [comment]
Ok, added.

**Comment by tyru** [comment]
Thanks!

**Pull request merged**
