### PR TITLE
support lambda 

### PR DESCRIPTION
**Pull request by haya14busa**
`:h lambda`

### CODE REVIEW

**Comment by haya14busa** [comment]
`let y = {x -> x} (1)`

Vim doesn't allow space between `}` and `(`, but this p-r allows it.
I guess vimlparser intends to be compatible to Vim as much as possible, so should we throws error for this case?

This is not related with lambda, but  `let y = (F) (1)` (note that space between braces) also isn't valid in Vim, but vimlparser parses this without error.

However, throwing error stops whole parsing and we cannot get nothing except error message.
It could be useful for linter or fixer not to throw errors and returns AST and leaves error handling for such tools. AST contains position, so they can handle it if they want.

What do you think?

**Comment by haya14busa** [comment]
`:call {x->x}(1)` is invalid in Vim too but p-r parses it. I guess we need to change parse_cmd_call if we want vimlparser to be compatible with Vim...

**Comment by mattn** [comment]
Please add test. Note that it need to skip test for lambda when vim7. 👍

**Comment by mattn** [comment]
Ah, I missed test files.

**Comment by mattn** [comment]
test_xxx_lambdaarg_last_comma passed. thank you.

**Pull request merged**
