### PR TITLE
Introduce byte offset

### LINKED ISSUE #65: Leading backslash causes wrong node.pos.i
via https://github.com/haya14busa/go-vimlparser/issues/43

I had created an issue on go-vimlparser, but this problem seems vim-vimlparser problem.

I want to extract `:function` ~ `:endfunction` block from Vim script source code,
but if the source code includes leading backslash, `node.pos.i` (index of original source code?) becomes wrong.

The following code is what I converted from [go-vimlparser issue](https://github.com/haya14busa/go-vimlparser/issues/43), which was written in Go, to Vim script.

```vim
let s:vimlparser = vimlparser#import()

function! s:run()
  let src = [
  \  'function! s:load_on()',
  \  '  imap <expr> <Tab> neosnippet#expandable_or_jumpable() ?',
  \  '\ "\<Plug>(neosnippet_expand_or_jump)" : "\<Tab>"',
  \  'endfunction',
  \]
  let r = s:vimlparser.StringReader.new(src)
  let p = s:vimlparser.VimLParser.new(0)
  let c = s:vimlparser.Compiler.new()
  let toplevel = p.parse(r)
  let func = toplevel.body[0]
  let body = s:extract_body(func, src)
  echo body
endfunction

function! s:extract_body(func, src)
  let pos = a:func.pos

  let endpos = a:func.endfunction.pos
  let endfunc = a:func.endfunction.ea
  let cmdlen = endfunc.argpos.i - endfunc.cmdpos.i
  let endpos.i += cmdlen

  return join(a:src, "\n")[pos.i : endpos.i]
endfunction

call s:run()
```

Output (the end of `n` is missing):

```
function! s:load_on()
  imap <expr> <Tab> neosnippet#expandable_or_jumpable() ?
\ "\<Plug>(neosnippet_expand_or_jump)" : "\<Tab>"
endfunctio
```

Specifying source code which does not include leading backslash was successful.

```vim
  let src = [
  \  'function! s:hello()',
  \  '  echo "hello"',
  \  'endfunction',
  \]
```

```
function! s:hello()
  echo "hello"
endfunction
```

## What I concern a little

The result was slightly different from original go-vimlparser behavior.
By go-vimlparser, the end of `on` (2 bytes) was missing.

```
function! s:load_on()
  imap <expr> <Tab> neosnippet#expandable_or_jumpable() ?
\ "\<Plug>(neosnippet_expand_or_jump)" : "\<Tab>"
endfuncti
```

### PR DESCRIPTION
**Pull request by haya14busa**
pos.i is actually "character offset" and it doesn't handle
line-continuation, so we cannot use pos.i to extract node from the
source with it.

Introduce pos.offset which represents byte offset which can be used
above cases.

FIX #65

### CODE REVIEW

**Comment by tyru** [comment]
Thanks for PR.
What is the status of this?
Can I help something?

**Comment by haya14busa** [comment]
It's ready to review except that I didn't write test in JavaScript (and Python).
viml_len implementation in JavaScript was wrong  so ideally we want to add a test for this, but I'm wondering how to write such tests in general ways.

**Comment by haya14busa** [comment]
FYI: @tyru 
https://github.com/haya14busa/go-vimlparser/pull/46

**Comment by haya14busa** [comment]
@mattn can you review this p-r when you have a time? Thanks!

**Comment by mattn** [comment]
AFAIK, python3 have same issue that len(str) return count of characters.

**Comment by haya14busa** [comment]
oh, that's true. fixed viml_len implementation in Python too.

**Comment by mattn** [comment]
LGTM

**Comment by haya14busa** [comment]
Could you merge this p-r?

**Comment by mattn** [comment]
Thank you

**Comment by haya14busa** [comment]
Thanks :+1:

**Pull request merged**
