### PR TITLE
Revisit Travis config, fix check target, update compiled files

### PR DESCRIPTION
**Pull request by blueyed**
It was initially meant for #46, but that is merged already.

I've worked on it further afterwards.

### CODE REVIEW

**Comment by blueyed** [comment]
Ready for review.
I will clean/squash it after your feedback then.

**Comment by mattn** [comment]
Sorry, my delay. Could you please fix conflict?

**Comment by blueyed** [comment]
@mattn 
Can you review it first, please?
(the conflicts are only in the compiled files, so trivial to fix)

**Comment by mattn** [comment]
Ah, sorry. Already done to review. LGTM.

**Comment by blueyed** [comment]
Ok, ready - assuming it is green.

**Comment by mattn** [comment]
Thank you

**Pull request merged**
