### PR TITLE
ci: Travis: branches: only build master branch

### PR DESCRIPTION
**Pull request by blueyed**
Ref: https://github.com/vim-jp/vim-vimlparser/pull/137#issuecomment-517934299

### CODE REVIEW

**Comment by tyru** [comment]
> The important one is the "pr" check (which tests the merge with master).
> The other checks the branch as-is (and there it might pass, although it fails for the merge).
> Therefore usually testing "pr" for PRs is fine - and happens when creating the PR from a fork (and not the main repo). When using the main repo for PRs also, you usually configure Travis to only build the master branch, and release tags.

hmm, I think so too maybe...
but "push" is really unnecessary...?

how do you think? > @mattn @haya14busa @thinca @ujihisa

**Comment by tyru** [comment]
I'm thinking why travis performing "push" by default, if it is totally unnecessary 🤔

**Comment by tyru** [comment]
I totally missed when the builds are created.
"push" is created after `git push`.
"pr" is created after pull request (as you said too).

"push" is useful to build all branches after `git push` automatically.
but vimlparser is developing in pull request based.
so I think only "pr" is enough.

I approve this in above reason.
after waiting some days, I will merge this.

**Comment by blueyed** [comment]
> I'm thinking why travis performing "push" by default, if it is totally unnecessary

Not really.. it should be done for "master" in most cases.. ;)
And people might use extra branches like "develop", "features" etc that should be build when things get merged into.

The thing here is that you are doing your PRs from branches of the main repo (and not your/a fork).

**Comment by ujihisa** [comment]
> after waiting some days, I will merge this.

181 days have passed. Let's merge this!

**Pull request merged**
